name: Run Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches-ignore: [gh-pages]
permissions:
  contents: read
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Set Node Environment
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
          check-latest: true

      - name: Update npm latest
        run: |
          npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm run test
